## Load the model

In [30]:
from shrinkbench.experiment import PruningExperiment, PruningClass
import torch
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathcal.calculator import *
from pathcal.loader import *
from pathcal.layers import *
from pathcal.helper import *

In [15]:
prev_paths = np.array([1,1,1,1])
weights = np.array([[1,3,2,1], [2,3,1,1]])
prev_paths = cal_linear_layer_paths(prev_paths, weights)
prev_paths

tensor([3, 2])

In [16]:
weights = np.array([[2,3], [2,1], [1,3]])
prev_paths = cal_linear_layer_paths(prev_paths, weights)
prev_paths

tensor([3, 0, 3])

In [ ]:
weights = np.array([[1,2,1], [3,2,1]])
prev_paths = cal_linear_layer_paths(prev_paths, weights)
prev_paths

torch.Size([2])


tensor([8, 5])

In [ ]:
def cal_conv_layer_paths(weights):
    # Calculate paths at current layer
    cur_path = weights.reshape(len(weights),-1)
    cur_path = (cur_path != 0).sum(axis=-1)
    # Calculate sum of all previous paths
    if prev_paths == None:
        total_prev_paths = 1
    else: 
        total_prev_paths = prev_paths.sum()
    # Calculate next paths
    next_path = cur_path * total_prev_paths
    return next_path

In [ ]:
cal_conv_layer_paths(prev_paths, weights)

tensor([15, 10])